---
title: "genentech_assignment_q2"
author: "Arundhati Rajan"
date: "2026-07-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# loading packages here
library(pharmaversesdtm)
library(admiral)
library(dplyr)
library(tidyr)
library(lubridate)
library(stringr)
library(haven)    
```

```{r}
# my approach involved using the ADSL dataset example on the Pharmaverse page and modifying it to create the new variables defined in the question 

#using the input datasets specified in the question
dm <- pharmaversesdtm::dm
ds <- pharmaversesdtm::ds
ex <- pharmaversesdtm::ex
ae <- pharmaversesdtm::ae
vs <- pharmaversesdtm::vs

# converting blank characters to NA values as missing values appear as blanks in the SAS format (datasets were originally in SAS and were then imported to R)
dm <- convert_blanks_to_na(dm)
ds <- convert_blanks_to_na(ds)
ex <- convert_blanks_to_na(ex)
ae <- convert_blanks_to_na(ae)
vs <- convert_blanks_to_na(vs)

#as mentioned in the reference ADSL article, the DM domain is used as the basis of the ADSL dataset
adsl <- dm%>%
  select(-DOMAIN)

#creation of variables

#AGEGR1 and AGEGR1N variables are created using the derive_vars_cat function from the admiral package. This is useful when more than one variable needs to be created for a given condition
agegr1_lookup <- exprs(
  ~condition,            ~AGEGR1, ~AGEGR1N,
  is.na(AGE),          "Missing",        4,
  AGE < 18,                "<18",        1,
  between(AGE, 18, 64),  "18-64",        2,
  !is.na(AGE),             ">64",        3
)

adsl <- adsl%>%
  derive_vars_cat(
  definition = agegr1_lookup
)

#the AGEGR9 and and AGEGR9N variables are created in a similar fashion based on the condition provided in the question
agegr9_lookup <- exprs(
  ~condition,             ~AGEGR9, ~AGEGR9N,
  AGE < 18,                  "<18",        1,
  between(AGE, 18, 50),  "18 - 50",        2,
  AGE > 50,                  ">50",        3
)
adsl <- adsl %>%
  derive_vars_cat(
    definition = agegr9_lookup
  )

#EXSTDTC and EXENDTC are processed and converted to datetime variables
ex_ext <- ex %>%
  derive_vars_dtm(
    dtc = EXSTDTC,
    new_vars_prefix = "EXST",
    time_imputation = "00:00:00" #if time is missing, it is imputed with 00:00:00 as described in the question
  ) %>%
  mutate(
    EXSTTMF = if_else(EXSTTMF == "S", NA_character_, EXSTTMF) #This essentially makes sure that the TRTSTMF flag gets set to NA if only seconds are missing
  )%>%
  derive_vars_dtm(
    dtc = EXENDTC,
    new_vars_prefix = "EXEN",
    time_imputation = "last"
  )

#The TRTSDTM and TRTSTMF variables have been created using the conditions mentioned in the question
adsl <- adsl %>%
  derive_vars_merged(
    dataset_add = ex_ext,
    filter_add = (EXDOSE > 0 |
      (EXDOSE == 0 &
        str_detect(EXTRT, "PLACEBO"))) & !is.na(EXSTDTM),
    new_vars = exprs(TRTSDTM = EXSTDTM, TRTSTMF = EXSTTMF),
    order = exprs(EXSTDTM, EXSEQ),
    mode = "first",
    by_vars = exprs(STUDYID, USUBJID)
  ) %>%

  derive_vars_merged(
    dataset_add = ex_ext,
    filter_add = (EXDOSE > 0 |
      (EXDOSE == 0 &
        str_detect(EXTRT, "PLACEBO"))) & !is.na(EXENDTM),
    new_vars = exprs(TRTEDTM = EXENDTM, TRTETMF = EXENTMF),
    order = exprs(EXENDTM, EXSEQ),
    mode = "last",
    by_vars = exprs(STUDYID, USUBJID)
  ) %>%
  
  derive_vars_dtm_to_dt(source_vars = exprs(TRTSDTM, TRTEDTM)) %>% #TRTSDT and TRTEDT created here 

  derive_var_trtdurd() %>% #TRTDURD calculated here using TRTSDT and TRTEDT
  
  #Safety Population Flag calculated below
  derive_var_merged_exist_flag(
    dataset_add = ex,
    by_vars = exprs(STUDYID, USUBJID),
    new_var = SAFFL,
    false_value = "N",
    missing_value = "N",
    condition = (EXDOSE > 0 | (EXDOSE == 0 & str_detect(EXTRT, "PLACEBO")))
  )

#Treatment variables TR01p and TRT01A mapped below
adsl <- adsl %>%
  mutate(TRT01P = ARM, TRT01A = ACTARM)

#ITTFL mapped to "Y" if [DM.ARM] not equal to missing else set to "N"
adsl <- adsl %>%
  mutate(
    ITTFL = if_else(!is.na(ARM), "Y", "N")
  )

#Disposition date derived from DS as it is an important variable required for other derivations
ds_ext <- derive_vars_dt(
  ds,
  dtc = DSSTDTC,
  new_vars_prefix = "DSST"
)

#End of Study Date i.e. EOSDT derived below
adsl <- adsl %>%
  derive_vars_merged(
    dataset_add = ds_ext,
    by_vars = exprs(STUDYID, USUBJID),
    new_vars = exprs(EOSDT = DSSTDT),
    filter_add = DSCAT == "DISPOSITION EVENT" & DSDECOD != "SCREEN FAILURE"
  )

#End of Study Status i.e. EOSSTT created below. The format_eosstt function provides end of study status. This function is applied only to those subjects with a disposition event.In case of missing values, EOSSTT takes the value "ONGOING".
format_eosstt <- function(x) {
  case_when(
    x %in% c("COMPLETED") ~ "COMPLETED",
    x %in% c("SCREEN FAILURE") ~ NA_character_,
    TRUE ~ "DISCONTINUED"
  )
}
adsl <- adsl %>%
  derive_vars_merged(
    dataset_add = ds,
    by_vars = exprs(STUDYID, USUBJID),
    filter_add = DSCAT == "DISPOSITION EVENT",
    new_vars = exprs(EOSSTT = format_eosstt(DSDECOD)),
    missing_values = exprs(EOSSTT = "ONGOING")
  )

#Death Date created below. Rules have been defined for imputation
adsl <- adsl %>%
  derive_vars_dt(
    new_vars_prefix = "DTH",
    dtc = DTHDTC,
    highest_imputation = "M",
    date_imputation = "first"
  )

#Randomization date,screen fail date and last retrieval date derived below using DSCAT and DSDECOD for filtering
adsl <- adsl %>%
  derive_vars_merged(
    dataset_add = ds_ext,
    by_vars = exprs(STUDYID, USUBJID),
    new_vars = exprs(RANDDT = DSSTDT),
    filter_add = DSDECOD == "RANDOMIZED",
  ) %>%
  derive_vars_merged(
    dataset_add = ds_ext,
    by_vars = exprs(STUDYID, USUBJID),
    new_vars = exprs(SCRFDT = DSSTDT),
    filter_add = DSCAT == "DISPOSITION EVENT" & DSDECOD == "SCREEN FAILURE"
  ) %>%
  derive_vars_merged(
    dataset_add = ds_ext,
    by_vars = exprs(STUDYID, USUBJID),
    new_vars = exprs(FRVDT = DSSTDT),
    filter_add = DSCAT == "OTHER EVENT" & DSDECOD == "FINAL RETRIEVAL VISIT"
  )

#Other death related duration variables, such as DTHADY (relative day of death) and LDDTHELD (numbers of days from last dose to death) have been derived using derive_vars_duration() function

adsl <- adsl %>%
  derive_vars_duration(
    new_var = DTHADY,
    start_date = TRTSDT,
    end_date = DTHDT
  ) %>%
  derive_vars_duration(
    new_var = LDDTHELD,
    start_date = TRTEDT,
    end_date = DTHDT,
    add_one = FALSE
  )


#RANDFL derived below. It is a population flag variable to indicate whether subject was randomized in the trial
assign_randfl <- function(x) {
  if_else(!is.na(x), "Y", NA_character_)
}
adsl <- adsl %>%
  mutate(
    RANDFL = assign_randfl(RANDDT)
  )

#DTHCAUS (cause of death) and DTHDOM (death domain) calculated below. The variables are derived by looking at death details collected from both AE and DS datasets. All qualifying events from both datasets are ordered, and the first recorded event is chosen for a given patient. 
adsl <- adsl %>%
  derive_vars_extreme_event(
    by_vars = exprs(STUDYID, USUBJID),
    events = list(
      event(
        dataset_name = "ae",
        condition = AEOUT == "FATAL",
        set_values_to = exprs(DTHCAUS = AEDECOD, DTHDOM = "AE"),
      ),
      event(
        dataset_name = "ds",
        condition = DSDECOD == "DEATH" & grepl("DEATH DUE TO", DSTERM),
        set_values_to = exprs(DTHCAUS = DSTERM, DTHDOM = "DS"),
      )
    ),
    source_datasets = list(ae = ae, ds = ds),
    tmp_event_nr_var = event_nr,
    order = exprs(event_nr),
    mode = "first",
    new_vars = exprs(DTHCAUS, DTHDOM)
  )

#Variable indicating region derived below
region1_lookup <- exprs(
  ~condition,                              ~REGION1, ~REGION1N,
  COUNTRY %in% c("CAN", "USA"),     "North America",         1,
  !is.na(COUNTRY),              "Rest of the World",         2,
  is.na(COUNTRY),                         "Missing",         3
)

#Variable indicating race derived below
racegr1_lookup <- exprs(
  ~condition, ~RACEGR1, ~RACEGR1N,
  RACE %in% c("WHITE"), "White", 1,
  RACE != "WHITE", "Non-white", 2,
  is.na(RACE), "Missing", 3
)

#Variable indicating category of death derived below
dthcgr1_lookup <- exprs(
  ~condition,                                                                                 ~DTHCGR1, ~DTHCGR1N,
  DTHDOM == "AE",                                                                      "ADVERSE EVENT",         1,
  !is.na(DTHDOM) & str_detect(DTHCAUS, "(PROGRESSIVE DISEASE|DISEASE RELAPSE)"), "PROGRESSIVE DISEASE",         2,
  !is.na(DTHDOM) & !is.na(DTHCAUS),                                                            "OTHER",         3,
  is.na(DTHDOM),                                                                         NA_character_,        NA
)
adsl <- adsl %>%
  derive_vars_cat(
    definition = region1_lookup
  ) %>%
  derive_vars_cat(
    definition = racegr1_lookup
  ) %>%
  derive_vars_cat(
    definition = dthcgr1_lookup
  )

#LSTAVLDT variable created below. The variable is derived by picking the maximum of last complete date of vital assessment with valid result, last complete onset date of AEs,last complete disposition date, and last date of treatment administration where patient received a valid dose. 
vs_lstavl <- vs %>%
  filter(!(is.na(VSSTRESN) & is.na(VSSTRESC))) %>%
  derive_vars_dt(
    new_vars_prefix = "VS",
    dtc = VSDTC
  ) %>%
  filter(!is.na(VSDT))

ae_lstavl <- ae %>%
  derive_vars_dt(
    new_vars_prefix = "AST",
    dtc = AESTDTC
  ) %>%
  filter(!is.na(ASTDT))

ds_lstavl <- ds %>%
  derive_vars_dt(
    new_vars_prefix = "DSST",
    dtc = DSSTDTC
  ) %>%
  filter(!is.na(DSSTDT))

#derive_vars_extreme_event function essentially pools all the valid dates from across the datasets, and picks the last date patient has documented clinical data
adsl <- adsl %>%
  derive_vars_extreme_event(
    by_vars = exprs(STUDYID, USUBJID),
    events = list(
      event(
        dataset_name = "vs_lstavl",
        order = exprs(VSDT),
        set_values_to = exprs(LSTAVLDT = VSDT)
      ),
      event(
        dataset_name = "ae_lstavl",
        order = exprs(ASTDT),
        set_values_to = exprs(LSTAVLDT = ASTDT)
      ),
      event(
        dataset_name = "ds_lstavl",
        order = exprs(DSSTDT),
        set_values_to = exprs(LSTAVLDT = DSSTDT)
      ),
      event(
        dataset_name = "adsl",
        condition = !is.na(TRTEDT),
        order = exprs(TRTEDT),
        set_values_to = exprs(LSTAVLDT = TRTEDT)
      )
    ),
    source_datasets = list(
      vs_lstavl = vs_lstavl,
      ae_lstavl = ae_lstavl,
      ds_lstavl = ds_lstavl,
      adsl = adsl
    ),
    tmp_event_nr_var = event_nr,
    order = exprs(LSTAVLDT),
    mode = "last",
    new_vars = exprs(LSTAVLDT)
  )


adsl <- adsl %>%
  arrange(STUDYID, USUBJID)

```

```{r}
#saving dataset in .csv format
write.csv(adsl,"/Users/arurajan/Documents/genentech_assignment/adsl.csv")
```

```{r}
#obtained log file by running the following commands in the terminal:
#cd /Users/arurajan/Documents/genentech_assignment
# Rscript -e "rmarkdown::render('02_create_adsl.Rmd')" > 02_create_adsl.log 2>&1
```

